--
-- FOREIGN KEYS [DROP]
-- 

ALTER TABLE "JOB_PARAM" DROP CONSTRAINT "FK_JOB_PARAM_JOBID" @@


--
-- JOB_LOG
-- 

CREATE TABLE "JOB_LOG" ("TENANTID"        NUMBER(19,0) NOT NULL,
                        "ID"              NUMBER(19,0) NOT NULL,
                        "JOBDESCRIPTORID" NUMBER(19,0) NOT NULL,
                        "RETRYNUMBER"     NUMBER(19,0) NULL,
                        "LASTUPDATEDATE"  NUMBER(19,0) NULL,
                        "LASTMESSAGE"     CLOB NULL,
						UNIQUE (tenantId, jobDescriptorId),
						PRIMARY KEY (tenantid, id)) @@
			   
INSERT INTO sequence (tenantid, id, nextid)
	SELECT ID, 72, 1 FROM tenant
	ORDER BY id ASC @@
	
	
--
-- FOREIGN KEYS [CREATE]
-- 

ALTER TABLE "JOB_LOG" ADD CONSTRAINT "FK_JOB_LOG_JOBID" FOREIGN KEY ("TENANTID","JOBDESCRIPTORID") REFERENCES "JOB_DESC" ("TENANTID", "ID") ON DELETE CASCADE @@
ALTER TABLE "JOB_PARAM" ADD CONSTRAINT "FK_JOB_PARAM_JOBID" FOREIGN KEY ("TENANTID","JOBDESCRIPTORID") REFERENCES "JOB_DESC" ("TENANTID", "ID") ON DELETE CASCADE @@	