ALTER TABLE user_ MODIFY COLUMN username VARCHAR(255);
ALTER TABLE user_ MODIFY COLUMN firstName VARCHAR(255);
ALTER TABLE user_ MODIFY COLUMN lastName VARCHAR(255);
ALTER TABLE user_ MODIFY COLUMN jobTitle VARCHAR(255);
ALTER TABLE user_contactinfo MODIFY COLUMN address VARCHAR(255);