ALTER TABLE user_ MODIFY username VARCHAR2(255)@@
ALTER TABLE user_ MODIFY firstName VARCHAR2(255)@@
ALTER TABLE user_ MODIFY lastName VARCHAR2(255)@@
ALTER TABLE user_ MODIFY jobTitle VARCHAR2(255)@@
ALTER TABLE user_contactinfo MODIFY address VARCHAR2(255)@@