ALTER TABLE user_ ALTER COLUMN username NVARCHAR(255)@@
ALTER TABLE user_ ALTER COLUMN firstName NVARCHAR(255)@@
ALTER TABLE user_ ALTER COLUMN lastName NVARCHAR(255)@@
ALTER TABLE user_ ALTER COLUMN jobTitle NVARCHAR(255)@@
ALTER TABLE user_contactinfo ALTER COLUMN address NVARCHAR(255)@@
ALTER TABLE queriable_log ALTER COLUMN userId NVARCHAR(255)@@