ALTER TABLE report ALTER COLUMN name NVARCHAR(50)
GO
ALTER TABLE report ALTER COLUMN description NVARCHAR(MAX)
GO
ALTER TABLE report ADD lastModificationDate NUMERIC(19,0) NOT NULL
GO
ALTER TABLE report ADD screenshot VARBINARY(MAX)
GO
ALTER TABLE report ADD content VARBINARY(MAX)
GO