SELECT tc.CONSTRAINT_NAME
FROM information_schema.TABLE_CONSTRAINTS tc
JOIN information_schema.KEY_COLUMN_USAGE kcu
  ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
WHERE tc.CONSTRAINT_SCHEMA = DATABASE()
  AND LOWER(tc.TABLE_NAME) = LOWER(?)
  AND tc.CONSTRAINT_TYPE = 'UNIQUE'
  AND LOWER(kcu.COLUMN_NAME) IN ('@COLUMN_NAMES@')
GROUP BY tc.CONSTRAINT_NAME
HAVING COUNT(*) = ?;