ALTER TABLE "PROCESS_DEFINITION" ADD "CONTENT_TENANTID" NUMBER(19, 0)@@
ALTER TABLE "PROCESS_DEFINITION" ADD "CONTENT_ID" NUMBER(19, 0)@@
CREATE TABLE process_content (
  tenantId NUMBER(19, 0) NOT NULL,
  id NUMBER(19, 0) NOT NULL,
  content CLOB NOT NULL,
  PRIMARY KEY (tenantid, id)
)@@