ALTER TABLE "DATASOURCEPARAMETER" DROP CONSTRAINT "FK_DSPARAM_TENID" @@
DROP TABLE "DATASOURCEPARAMETER" @@
DROP TABLE "DATASOURCE" @@
DELETE FROM "SEQUENCE" WHERE "ID" = 50 @@
DELETE FROM "SEQUENCE" WHERE "ID" = 51 @@