--
-- ARCH_FLOWNODE_INSTANCE
-- 

ALTER TABLE "ARCH_FLOWNODE_INSTANCE" ADD "EXECUTEDBYDELEGATE" NUMBER(19,0) @@


--
-- FLOWNODE_INSTANCE
-- 

ALTER TABLE "FLOWNODE_INSTANCE" MODIFY "PRIORITY" SMALLINT @@
ALTER TABLE "FLOWNODE_INSTANCE" ADD "EXECUTEDBYDELEGATE" NUMBER(19,0) @@

--
-- Datas
-- 

UPDATE flownode_instance SET executedbydelegate = executedby @@
UPDATE arch_flownode_instance SET executedbydelegate = executedby @@