ALTER TABLE process_instance ALTER COLUMN stringIndex1 TYPE VARCHAR(255);
ALTER TABLE process_instance ALTER COLUMN stringIndex2 TYPE VARCHAR(255);
ALTER TABLE process_instance ALTER COLUMN stringIndex3 TYPE VARCHAR(255);
ALTER TABLE process_instance ALTER COLUMN stringIndex4 TYPE VARCHAR(255);
ALTER TABLE process_instance ALTER COLUMN stringIndex5 TYPE VARCHAR(255);

ALTER TABLE arch_process_instance ALTER COLUMN stringIndex1 TYPE VARCHAR(255);
ALTER TABLE arch_process_instance ALTER COLUMN stringIndex2 TYPE VARCHAR(255);
ALTER TABLE arch_process_instance ALTER COLUMN stringIndex3 TYPE VARCHAR(255);
ALTER TABLE arch_process_instance ALTER COLUMN stringIndex4 TYPE VARCHAR(255);
ALTER TABLE arch_process_instance ALTER COLUMN stringIndex5 TYPE VARCHAR(255);

ALTER TABLE group_ ALTER COLUMN name TYPE VARCHAR(255);
ALTER TABLE group_ ALTER COLUMN displayName TYPE VARCHAR(255);
ALTER TABLE group_ ALTER COLUMN parentPath TYPE VARCHAR(1024);

ALTER TABLE role ALTER COLUMN name TYPE VARCHAR(255);
ALTER TABLE role ALTER COLUMN displayName TYPE VARCHAR(255);

ALTER TABLE user_ ALTER COLUMN delegeeUserName TYPE VARCHAR(255);
