ALTER TABLE user_ DROP COLUMN iconpath;
ALTER TABLE user_ DROP COLUMN iconname;
ALTER TABLE group_ DROP COLUMN iconpath;
ALTER TABLE group_ DROP COLUMN iconname;
ALTER TABLE role DROP COLUMN iconpath;
ALTER TABLE role DROP COLUMN iconname;