ALTER TABLE user_ ALTER username TYPE VARCHAR(255);
ALTER TABLE user_ ALTER firstName TYPE VARCHAR(255);
ALTER TABLE user_ ALTER lastName TYPE VARCHAR(255);
ALTER TABLE user_ ALTER jobTitle TYPE VARCHAR(255);
ALTER TABLE user_contactinfo ALTER address TYPE VARCHAR(255);