--
-- FOREIGN KEYS [DROP]
-- 

ALTER TABLE "TRANSITION_INSTANCE" DROP CONSTRAINT "FK_TRANSINST_TENID" @@


--
-- TRANSITION_INSTANCE
-- 

DROP TABLE "TRANSITION_INSTANCE" @@
DELETE FROM "SEQUENCE" WHERE "ID" = 10013 @@