--
-- ARCH_DATA_INSTANCE
-- 

ALTER TABLE "ARCH_DATA_INSTANCE" ADD "CLOBVALUE_TEMP" CLOB @@
UPDATE "ARCH_DATA_INSTANCE" SET "CLOBVALUE_TEMP" = "CLOBVALUE" @@
ALTER TABLE "ARCH_DATA_INSTANCE" DROP COLUMN "CLOBVALUE" @@
ALTER TABLE "ARCH_DATA_INSTANCE" RENAME COLUMN "CLOBVALUE_TEMP" TO "CLOBVALUE" @@