--
-- ARCH_PROCESS_INSTANCE
-- 

UPDATE "ARCH_PROCESS_INSTANCE" SET "STARTEDBY" = 0 @@
ALTER TABLE "ARCH_PROCESS_INSTANCE" MODIFY "STARTEDBY" NOT NULL @@
ALTER TABLE "ARCH_PROCESS_INSTANCE" ADD "STARTEDBYDELEGATE" NUMBER(19,0) @@


--
-- PROCESS_INSTANCE
-- 

UPDATE "PROCESS_INSTANCE" SET "STARTEDBY" = 0 @@
ALTER TABLE "PROCESS_INSTANCE" MODIFY "STARTEDBY" NOT NULL @@
ALTER TABLE "PROCESS_INSTANCE" ADD "STARTEDBYDELEGATE" NUMBER(19,0) DEFAULT 0 NOT NULL @@