--
-- Command
-- 
ALTER TABLE command MODIFY name VARCHAR2(50 CHAR) @@
ALTER TABLE command MODIFY description VARCHAR2(1024 CHAR) @@
ALTER TABLE command MODIFY IMPLEMENTATION VARCHAR2(100 CHAR) @@


--
-- Platform_command
-- 

ALTER TABLE platformCommand MODIFY name VARCHAR2(50 CHAR) UNIQUE @@
ALTER TABLE platformCommand MODIFY description VARCHAR2(1024 CHAR) @@
ALTER TABLE platformCommand MODIFY IMPLEMENTATION VARCHAR2(100 CHAR) @@
