SELECT
    c.TABLE_NAME,
    c.CONSTRAINT_NAME
FROM
    information_schema.TABLE_CONSTRAINTS c
WHERE LOWER( c.TABLE_NAME ) = LOWER( ? )
    AND LOWER( c.CONSTRAINT_NAME ) = LOWER( ? )
    AND c.CONSTRAINT_TYPE = 'FOREIGN KEY'