--
-- Platform
-- 
ALTER TABLE platform MODIFY version VARCHAR2(50 CHAR) @@
ALTER TABLE platform MODIFY previousVersion VARCHAR2(50 CHAR) @@
ALTER TABLE platform MODIFY initialVersion VARCHAR2(50 CHAR) @@
ALTER TABLE platform MODIFY createdBy VARCHAR2(50 CHAR) @@


--
-- Tenant
-- 
ALTER TABLE tenant MODIFY createdBy VARCHAR2(50 CHAR) @@
ALTER TABLE tenant MODIFY description VARCHAR2(255 CHAR) @@
ALTER TABLE tenant MODIFY iconName VARCHAR2(50 CHAR) @@
ALTER TABLE tenant MODIFY iconPath VARCHAR2(255 CHAR) @@
ALTER TABLE tenant MODIFY name VARCHAR2(50 CHAR) @@
ALTER TABLE tenant MODIFY status VARCHAR2(15 CHAR) @@
