ALTER TABLE "WAITING_EVENT" ADD "PROGRESS" SMALLINT DEFAULT 0 @@
UPDATE "WAITING_EVENT" SET "PARENTPROCESSINSTANCEID" = "ROOTPROCESSINSTANCEID" WHERE "PARENTPROCESSINSTANCEID" = -1 @@
DELETE FROM "MESSAGE_INSTANCE" WHERE "HANDLED" = 1 @@